name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable
        # THIS LINE BELOW FIXES THE CHOWN ERROR
        env:
          USER: root

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: crown-battle
          path: bin/*.apk
          
